# Generated by Django 5.1.3 on 2024-11-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_User', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Vendor', 'Vendor'), ('Customer', 'Customer')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
