# Generated by Django 5.1.3 on 2024-11-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_User', '0006_alter_cart_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
